---
- name: podman ps simples
  hosts: all
  gather_facts: false
  become: true          # remova se seus containers são rootless no usuário remoto

  vars:
    include_all: false  # defina true para usar "podman ps -a"

  tasks:
    - name: Executar podman ps
      ansible.builtin.command: >
        podman ps {{ '--all' if include_all else '' }}
      register: ps
      changed_when: false

    - name: Mostrar saída
      ansible.builtin.debug:
        var: ps.stdout_lines

